# Generated by Django 4.2.6 on 2023-10-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutPaciente', models.CharField(max_length=20)),
                ('nomPaciente', models.CharField(max_length=100)),
                ('apePaciente', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('contraPaciente', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
    ]
